# Generated by Django 5.1 on 2024-09-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_order_item_name_remove_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
